# Amap Data Crawler - Batch crawl all cities
# Generated by Python - do not edit header
import urllib.request, ssl, json, time, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from database import get_conn
KEY = os.environ.get("AMAP_KEY", "fc5ea342775f94afaf8aec42694fdb4c")
ctx = ssl._create_unverified_context()
hdr = {'User-Agent': 'Mozilla/5.0'}
SEARCH_URL = 'https://restapi.amap.com/v3/place/text?'
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')

def search(city, types, keywords, page, offset):
    q = []
    q.append('key=' + KEY)
    if keywords:
        q.append('keywords=' + urllib.request.quote(keywords))
    if types:
        q.append('types=' + urllib.request.quote(types))
    if city:
        q.append('city=' + urllib.request.quote(city))
    q.append('offset=' + str(offset))
    q.append('page=' + str(page))
    q.append('extensions=all')
    url = SEARCH_URL + '&'.join(q)
    req = urllib.request.Request(url, headers=hdr)
    r = urllib.request.urlopen(req, timeout=15, context=ctx)
    return json.loads(r.read().decode())

def crawl_city(city, type_code, type_name, max_pages):
    all_pois = []
    for page in range(1, max_pages + 1):
        try:
            data = search(city, type_code, None, page, 20)
            pois = data.get('pois', [])
            if not pois:
                break
            all_pois.extend(pois)
            print('  Page ' + str(page) + ': +' + str(len(pois)) + ' POIs, total ' + str(len(all_pois)))
            time.sleep(0.2)
        except Exception as e:
            print('  Error: ' + str(e)[:60])
            time.sleep(1)
    return all_pois

def save_results(city, type_name, pois):
    os.makedirs(DATA_DIR, exist_ok=True)
    filename = 'amap_' + city + '_' + type_name + '.json'
    filepath = os.path.join(DATA_DIR, filename)
    data = {'city': '', 'type': '', 'count': 0, 'pois': []}
    data['city'] = city
    data['type'] = type_name
    data['count'] = len(pois)
    data['pois'] = pois
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print('Saved ' + str(len(pois)) + ' POIs to ' + filepath)
    return filepath
